version: 1.0
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s %(levelname)s (%(pathname)s, %(module)s, %(funcName)s, %(lineno)d): %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: 'dbsupport/logs/info.log'
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: 'dbsupport/logs/errors.log'
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
loggers:
  info:
    level: INFO
    handlers: [info_file_handler]
    propagate: no
  error:
    level: INFO
    handlers: [error_file_handler]
    propagate: no
root:
  level: INFO
  handlers: [console, info_file_handler, error_file_handler]  